name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello World!"
        
      - name: Multiline Command
        run: |
          pandas -v
          python -V
